parameters:
  artifactName: ''

steps:
- task: CopyFiles@2
  displayName: Copy source files to drop location
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}/'
    Contents: |
      pipeline/storage/**
      !**/.gitkeep
      !.git/**/*

- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}'
    ArtifactName: '${{ parameters.artifactName }}'

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)