variables:
  environment: 'dev'
  serviceConnectionName: 'assignment-${{ variables.environment }}'
  resourceGroupName: 'assignment-${{ variables.environment }}'
  location: 'location'
  subscriptionId: 'subscriptionId'
  parametersFile: '$(Pipeline.Workspace)\drop\react-app\parameters\${{ variables.environment }}.json'