variables:
  environment: 'dev'
  serviceConnectionName: 'assignment-${{ variables.environment }}'
  resourceGroupName: 'assignment-${{ variables.environment }}'
  location: 'West Europe'
  subscriptionId: '<subscriptionId>'
  parametersFile: '$(Pipeline.Workspace)\drop\react-app\parameters\${{ variables.environment }}.json'