variables:
  environment: 'dev'
  serviceConnectionName: 'assignment-${{ variables.environment }}'
  resourceGroupName: 'rg-devops-assignment-${{ variables.environment }}'
  location: 'West Europe'
  subscriptionId: '<subscriptionId>'
  parametersFile: '$(Pipeline.Workspace)\drop\springboot-app\parameters\${{ variables.environment }}.json'
  containerRegistry: 'devops-assignment-acr-${{ variables.environment }}'
  imageName: 'springbootapp'
  latestTag: 'latest'